# Generated by dockstep

FROM alpine:latest

RUN \
    echo "Setting up base environment" && \
    apk add --no-cache bash curl

# Stage: base

RUN \
    echo "Installing Go on base" && \
    apk add --no-cache go && \
    go version

# Stage: install-go

RUN \
    echo "Setting up full-stack environment" && \
    apk add --no-cache nodejs npm && \
    go version && \
    node --version && \
    echo "Full-stack setup complete"
