# Generated by dockstep

FROM alpine:latest

RUN \
    echo "Installing Go" && \
    apk add --no-cache go && \
    go version

# Stage: install-go

WORKDIR /app

RUN \
    echo "Running script that depends on Go" && \
    go version && \
    echo "Script completed successfully"
