# Generated by dockstep

FROM alpine:latest

RUN echo 'new block - this block does nothing'

# Stage: base

RUN \
    apk update && \
    apk add go && \
    go version

# Stage: install go

RUN go version
