version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  # npm (UI dependencies)
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "leonardmarcq"
    assignees:
      - "leonardmarcq"
